@startuml

interface Interface1 {
    void operation1();
}
interface Interface2 {
    void operation2();
    void operation3();
}
interface Interface3 {
    void operation4();
    void operation5();
}
class A extends Interface1, Interface2

class B implements Interface1, Interface2
class D implements Interface1, Interface3

class C extends Interface1, Interface3

@enduml